=== umesh2002-sys/XML_WebPortal/catalog_20049086.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="main">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="shopLogo"/>
                <xs:element name="shopName">
                    <xs:complexType>
                        <xs:simpleContent>
                            <!-- extension element extends an existing simpleType or complexType element -->
                            <xs:extension base="xs:string">
                                <!-- xs:unsignedInt is the integers between 0 and 4294967295 -->
                                <xs:attribute name="regID" type="xs:unsignedInt" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="shopDiscription" type="xs:string"/>

                <xs:element name="comapanyAddress">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Unitrd Kingdom, London"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="PhoneNumber">
                    <xs:simpleType>
                        <!-- restriction for phonenumber -->
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\([+0-9]{3}\) [0-9]{4} [0-9]{6}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="URL">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="www.oriostore.com.uk"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="cards">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:choice maxOccurs="unbounded">
                                <xs:element name="cardImage">
                                    <xs:complexType>
                                        <xs:attribute name="id" type="xs:string" use="required"/>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="card">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="name" type="xs:string"/>
                                            <xs:element name="description" type="xs:string"/>
                                            <xs:element name="type">
                                                <xs:complexType>
                                                    <xs:simpleContent>
                                                        <xs:extension>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Card type: Digital Card"/>
                                                                <xs:enumeration value="Card type: Physical Card"/>
                                                            </xs:restriction>
                                                            
                                                            <!-- attributes of element type -->
                                                            <xs:attribute name="type" type="xs:string" use="required"/>
                                                        </xs:extension>
                                                    </xs:simpleContent>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="Region">
                                                <xs:simpleType>
                                                    <xs:simpleContent>
                                                        <xs:extension>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Region: United Kingdom"/>
                                                                <xs:enumeration value="Region: Global"/>
                                                            </xs:restriction>
                                                        </xs:extension>
                                                    </xs:simpleContent>
                                                </xs:simpleType>
                                            </xs:element>
                                            <xs:element name="Developer" type="xs:string"/>
                                            <xs:element name="publisher" type="xs:string"/>
                                            <xs:element name="platform" type="xs:string"/>
                                            <xs:element minOccurs="0" name="genre" type="xs:string"/>
                                            <xs:element name="rate" type="xs:string"/>
                                            <xs:element minOccurs="0" name="dmode" type="xs:string"/>
                                            <xs:element minOccurs="0" name="dtime" type="xs:string"/>
                                            <xs:element minOccurs="0" name="sellingRate" type="xs:string"/>
                                            <xs:element minOccurs="0" name="responceRate" type="xs:string"/>
                                            <xs:element name="quantity" type="xs:string"/>
                                            <xs:element name="price" type="xs:string"/>
                                            <xs:element name="product">
                                                <xs:complexType> 
                                                    <xs:simpleContent>
                                                        <xs:extension>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Available"/>
                                                                <xs:enumeration value="Out of Stock"/>
                                                            </xs:restriction>
                                                            <!-- product attributes -->
                                                            <xs:attribute name="type" type="xs:string" use="required"/>
                                                        </xs:extension>
                                                    </xs:simpleContent>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                        <!-- card attributes -->
                                        <xs:attribute name="id" type="xs:string" use="required"/>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== umesh2002-sys/XML_WebPortal/catalog_20049086.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!--
    Name: Umesh Shahu Shrestha
    LondonMetID: 20049086
    CollegeId: np01cp4s210288
    class: C11
-->
<main xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_20049086.xsd">
    <shopLogo></shopLogo>
    <shopName regID="20049086">Orio</shopName>
    <shopDiscription>
    <![CDATA[
        Orio is one of the most successful store located in London, Unitrd Kingdom which sells phusical and degital gift cards. With the help of gift card a user can make purchases at retail stores, gas stations, restaurants and other locations.
    ]]>
    </shopDiscription>
    <comapanyAddress>Unitrd Kingdom, London</comapanyAddress>
    <PhoneNumber>+44 7911 123456</PhoneNumber>
    <URL>www.oriostore.com.uk</URL>
    <cards>
        <cardImage id="img1"></cardImage>
        <!--  card of Pubg -->
        <card id="c1">
            <name>Pubg</name>
            <description>
            <![CDATA[
                PUBG MOBILE has the highest fidelity items and gameplay experience. PUBG MOBILE can fulfill any wish you might have. Choose from countless firearms and test your marksmanship. Further more details checkout official webside www.pubgmoblie.com.uk.
            ]]>
            </description>
            <!-- Optional Physical Card and Digital card-->
            <type type="digital">Card Type: Digital Card</type>
            <Region>Region: United Kingdom</Region>
            <Developer>Developer: Lightspeed and Quantum</Developer>
            <publisher>Publisher: Tencent Games and Krafton</publisher>
            <platform>Platforms: Android, IOS </platform>
            <!-- Optional -->
            <rate>Rating: 4.2/5 Stars </rate>
            <sellingRate>positive seller Rating: 89% </sellingRate>
            <responceRate>Chat Response Rate: 87% </responceRate>
            <quantity>Quantity: 10</quantity>
            <price>Price: £32</price>
            <!-- Optional Available or N/A-->
            <product type="Available">Available </product>
        </card>

        <cardImage id="img2"></cardImage>

        <!--  card of Google Play -->
        <card id="c2">
            <name>Google Play</name>
            <description>
            <![CDATA[
                Google Play, also branded as the Google Play Store and formerly Android Market, is a digital distribution service operated and developed by Google. Further more details checkout official webside www.playstore.com.uk.
            ]]>
            </description>
            <!-- Optional Physical Card and Digital card-->
            <type type="digital">Card Type: Digital Card</type>
            <Region>Region: United Kingdom</Region>
            <Developer>Developer: Lightspeed and Quantum</Developer>
            <publisher>Publisher: Tencent Games and Krafton</publisher>
            <platform>Platforms: Android, Wear OS, Chrome OS, Web </platform>
            <genre> Genre: Gift Card </genre>
            <!-- Optional -->
            <rate>Rating: 4.3/5 Stars </rate>
            <sellingRate>positive seller Rating: 87% </sellingRate>
            <responceRate>Chat Response Rate: 82% </responceRate>
            <quantity>Quantity: 23</quantity>
            <price>Price: £45</price>
            <!-- Optional Available or N/A-->
            <product type="Available">Available </product>
        </card>

        <cardImage id="img3"></cardImage>

        <!--  card code of playstation -->
        <card id="c3">
            <name>Play Station</name>
            <description>
            <![CDATA[
                PlayStation, video game console released in 1994 by Sony Computer Entertainment. The PlayStation, one of a new generation of 32-bit consoles, signaled Sony's rise to power in the video game world. Further more details checkout official webside www.PlayStation.com.uk.
            ]]>
            </description>
            <!-- Optional Physical Card and Digital card-->
            <type type="digital">Card Type: Digital Card</type>
            <Region>Region: United Kingdom</Region>
            <Developer>Sony Interactive Entertainment</Developer>
            <publisher>Eastasiasoft, Ratalaika Games and Bandai Namco Entertainment</publisher>
            <platform>Platforms: PS4, PS5 and PC</platform>
            <!-- Optional -->
            <rate>Rating: 4.1/5 Stars </rate>
            <sellingRate>positive seller Rating: 93% </sellingRate>
            <responceRate>Chat Response Rate: 91% </responceRate>
            <quantity>Quantity: 0</quantity>
            <price>Price: £22</price>
            <!-- Optional Available or N/A-->
            <product type="N/A">Out Of Stock</product>
        </card>

        <cardImage id="img4"></cardImage>

        <!--  card of  Clash of Clans -->
        <card id="c4">
            <name>Clash of Clans</name>
            <description>
            <![CDATA[
                Clash of Clans is a 2012 free-to-play mobile strategy video game developed and published by Finnish game developer Supercell. Further more details checkout official webside www.supercell.com.uk.
            ]]>
            </description>
            <!-- Optional Physical Card and Digital card-->
            <type type="physical">Card type: Physical Card</type>
            <Region>Region: United Kingdom</Region>
            <Developer>Developer: Supercell</Developer>
            <publisher>Publisher: Supercell</publisher>
            <platform>Platforms: Android, IOS</platform>
            <genre>Genre: Strategy </genre>
            <!-- Optional -->
            <rate>Rating: 4.3/5 Stars </rate>
            <sellingRate>positive seller Rating: 78% </sellingRate>
            <responceRate>Chat Response Rate: 72% </responceRate>
            <quantity>Quantity: 12</quantity>
            <price>Price: £27</price>
            <!-- Optional Available or N/A-->
            <product type="Available">Available </product>
        </card>

        <cardImage id="img5"></cardImage>

        <!--  card of iTunes -->
        <card id="c5">
            <name>iTunes</name>
            <description>
            <![CDATA[
               iTunes is a software program that acts as a media player, media library, mobile device management utility, and the client app for the iTunes Store. Further more details checkout official webside www.appleInc.com.uk.
            ]]>
            </description>
            <!-- Optional Physical Card and Digital card-->
            <type type="physical">Card type: Physical Card</type>
            <Region>Region: United Kingdom</Region>
            <Developer>Developer: Apple Inc</Developer>
            <publisher>Publisher: Apple Inc</publisher>
            <platform>Platforms: Android, IOS, Laptop</platform>
            <genre>Genre: Gift Card </genre>
            <!-- Optional -->
            <rate>Rating: 4.4/5 Stars </rate>
            <sellingRate>positive seller Rating: 88% </sellingRate>
            <responceRate>Chat Response Rate: 79% </responceRate>
            <quantity>Quantity: 2</quantity>
            <price>Price: £67</price>
            <!-- Optional Available or N/A-->
            <product type="Available">Available </product>
        </card>

        <cardImage id="img6"></cardImage>

        <!--  card of Nintendo -->
        <card id="c6">
            <name>Nintendo</name>
            <description>
            <![CDATA[
               Nintendo Co., Ltd. is a Japanese multinational video game company. It develops video games and video game consoles. Further more details checkout official webside www.nintendo.com.uk.
            ]]>
            </description>
            <!-- Optional Physical Card and Digital card-->
            <type type="digital">Card type: Digital Card</type>
            <Region>Region: United Kingdom</Region>
            <Developer>Developer: Nintendo Company Ltd</Developer>
            <publisher>Publisher: Nintendo Company Ltd</publisher>
            <platform>Platforms: PS3, PlayStation, Laptop</platform>
            <genre>Genre: Gift Card </genre>
            <!-- Optional -->
            <rate>Rating: 3.9/5 Stars </rate>
            <sellingRate>positive seller Rating: 78% </sellingRate>
            <responceRate>Chat Response Rate: 59% </responceRate>
            <quantity>Quantity: 4</quantity>
            <price>Price: £167</price>
            <!-- Optional Available or N/A-->
            <product type="Available">Available </product>
        </card>

        <cardImage id="img7"></cardImage>

        <!--  card of Free Fire -->
        <card id="c7">
            <name>Free Fire</name>
            <description>
            <![CDATA[
               Garena Free Fire, also known as Free Fire, is a battle royale game, developed by 111dots Studio and published by Garena for Android and iOS. Further more details checkout official webside www.ff.garena.com.uk.
            ]]>
            </description>
            <!-- Optional Physical Card and Digital card-->
            <type type="physical">Card type: Physical Card</type>
            <Region>Region: United Kingdom</Region>
            <Developer>Developer: Apple Inc</Developer>
            <publisher>Publisher:  Garena</publisher>
            <platform>Platforms: Android, IOS</platform>
            <genre>Genre: Battle royale game </genre>
            <!-- Optional -->
            <rate>Rating: 4.2/5 Stars </rate>
            <dmode> Delivery mode: Supercell ID </dmode>
            <dtime>Delivery time: 30 mins </dtime>
            <quantity>Quantity: 8</quantity>
            <price>Price: £19</price>
            <!-- Optional Available or N/A-->
            <product type="Available">Available </product>
        </card>

        <cardImage id="img8"></cardImage>

        <!-- card of X-Box -->
        <card id="c8">
            <name>X-Box</name>
            <description>
